package verkehrschaos;

/**
 * verkehrschaos/ELocationInUse.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from verkehrschaos.idl Samstag, 4. April 2015 19:41 Uhr MESZ
 */

public final class ELocationInUse extends org.omg.CORBA.UserException{
    public String msg = null;

    public ELocationInUse(){
        super(ELocationInUseHelper.id());
    } // ctor

    public ELocationInUse(String _msg){
        super(ELocationInUseHelper.id());
        msg = _msg;
    } // ctor

    public ELocationInUse(String $reason, String _msg){
        super(ELocationInUseHelper.id() + "  " + $reason);
        msg = _msg;
    } // ctor

} // class ELocationInUse
