package verkehrschaos;

/**
 * verkehrschaos/Truck.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from verkehrschaos.idl Samstag, 4. April 2015 19:41 Uhr MESZ
 */

public interface Truck extends TruckOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity{} // interface Truck
