package gcd.Coordinator;


/**
* gcd/Coordinator/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

public interface CoordinatorOperations 
{

  /*
              * Liefert eine Liste mit allen Startern zurueck.
              */
  gcd.Starter.Starter[] getAllStarters ();

  /*
              * Meldet false wenn der Koordinator neue Auftraege annehmen kann
              */
  boolean isBusy ();

  /*
              * Startet die Berechnung der
              */
  void calculateGcd (int minNoProcesses, int maxNoProcesses, int minDelay, int maxDelay, int tTimeout, int gcd);

  /*
              * Schickt das Ergebnis der Rechnung an den Koordinator
              */
  void calculationComplete (boolean complete, int result, String processID, int seq);

  /*
              * Meldet einen Starter beim Koordinator an.
              */
  void registerStarter (gcd.Starter.Starter starter);

  /*
              * Meldet einen ggt-Prozess beim Koordinator an.
              */
  void registerGcdProcess (gcd.Starter.GcdProcess process);

  /*
              * Faehrt das System runter.
              */
  void shutDown ();
} // interface CoordinatorOperations
