package gcd.Starter;


/**
* gcd/Starter/GcdProcessOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

public interface GcdProcessOperations 
{

  /*
              * Initialisiert den ggT-Prozess
              */
  void initGcdProcess (gcd.Starter.GcdProcess rightNeighbour, gcd.Starter.GcdProcess leftNeighbour, int startvalue, int delay, monitor.Monitor gcdMonitor);

  /*
              * Liefert den Namen des Prozesses.
              */
  String getName ();

  /*
              * Liefert den aktuellen Wert des Prozesses.
              */
  int getNumber ();

  /*
              * Empfaengt BerechnugsAuftrag vom Koordinator
              */
  void startGcdAlgorithm ();

  /*
              * Empfaengt BerechnugsAuftrag vom Nachbarn
              */
  void calculateMsg (String sender, int value);

  /*
              * Empfaengt TerminierungsAuftrag vom Nachbarn
              */
  void terminateGcdCalculation (String sender, int value);
} // interface GcdProcessOperations
