package gcd.Starter;


/**
* gcd/Starter/StarterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

public interface StarterOperations 
{

  /*
              * Liefert die ID des Starters.
              */
  String getId ();

  /*
              * Startet die uebergebene Anzahl an GgT-Prozessen
              */
  void startGcdProcesses (int anzahl);

  /*
              * Beendet alle GgT-Prozesse
              */
  void endGcdProcesses ();

  /*
              * Meldet dem Starter die endgültige beendigung eines Prozesses
              */
  void processFinished ();

  /*
              * Beendet den Starter und alle GgT-Prozesse
              */
  void shutDown ();
} // interface StarterOperations
