
package hawmetering;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HAWSensorWebserviceService", targetNamespace = "http://hawmetering/", wsdlLocation = "http://localhost:20000/hawmetering/sensor/?wsdl")
public class HAWSensorWebserviceService
    extends Service
{

    private final static URL HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException HAWSENSORWEBSERVICESERVICE_EXCEPTION;
    private final static QName HAWSENSORWEBSERVICESERVICE_QNAME = new QName("http://hawmetering/", "HAWSensorWebserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:20000/hawmetering/sensor/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION = url;
        HAWSENSORWEBSERVICESERVICE_EXCEPTION = e;
    }

    public HAWSensorWebserviceService() {
        super(__getWsdlLocation(), HAWSENSORWEBSERVICESERVICE_QNAME);
    }

    public HAWSensorWebserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HAWSENSORWEBSERVICESERVICE_QNAME, features);
    }

    public HAWSensorWebserviceService(URL wsdlLocation) {
        super(wsdlLocation, HAWSENSORWEBSERVICESERVICE_QNAME);
    }

    public HAWSensorWebserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HAWSENSORWEBSERVICESERVICE_QNAME, features);
    }

    public HAWSensorWebserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HAWSensorWebserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HAWSensorWebservice
     */
    @WebEndpoint(name = "HAWSensorWebservicePort")
    public HAWSensorWebservice getHAWSensorWebservicePort() {
        return super.getPort(new QName("http://hawmetering/", "HAWSensorWebservicePort"), HAWSensorWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HAWSensorWebservice
     */
    @WebEndpoint(name = "HAWSensorWebservicePort")
    public HAWSensorWebservice getHAWSensorWebservicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hawmetering/", "HAWSensorWebservicePort"), HAWSensorWebservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HAWSENSORWEBSERVICESERVICE_EXCEPTION!= null) {
            throw HAWSENSORWEBSERVICESERVICE_EXCEPTION;
        }
        return HAWSENSORWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
