package gcd.Coordinator;

/**
* gcd/Coordinator/CoordinatorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

public final class CoordinatorHolder implements org.omg.CORBA.portable.Streamable
{
  public gcd.Coordinator.Coordinator value = null;

  public CoordinatorHolder ()
  {
  }

  public CoordinatorHolder (gcd.Coordinator.Coordinator initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gcd.Coordinator.CoordinatorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gcd.Coordinator.CoordinatorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gcd.Coordinator.CoordinatorHelper.type ();
  }

}
