package gcd.Coordinator;


/**
* gcd/Coordinator/StarterListHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

abstract public class StarterListHelper
{
  private static String  _id = "IDL:gcd/Coordinator/StarterList:1.0";

  public static void insert (org.omg.CORBA.Any a, gcd.Starter.Starter[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static gcd.Starter.Starter[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = gcd.Starter.StarterHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (gcd.Coordinator.StarterListHelper.id (), "StarterList", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static gcd.Starter.Starter[] read (org.omg.CORBA.portable.InputStream istream)
  {
    gcd.Starter.Starter value[] = null;
    int _len0 = istream.read_long ();
    value = new gcd.Starter.Starter[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = gcd.Starter.StarterHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, gcd.Starter.Starter[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      gcd.Starter.StarterHelper.write (ostream, value[_i0]);
  }

}
