package verkehrschaos;

/**
 * verkehrschaos/Streets.java . Generated by the IDL-to-Java compiler (portable), version "3.2" from verkehrschaos.idl Samstag, 4. April 2015 19:40 Uhr MESZ
 */

public interface Streets extends StreetsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity{} // interface Streets
