package gcd.Starter;

/**
* gcd/Starter/GcdProcessHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from distributed-algorithm.idl
* Dienstag, 19. Mai 2015 08:38 Uhr MESZ
*/

public final class GcdProcessHolder implements org.omg.CORBA.portable.Streamable
{
  public gcd.Starter.GcdProcess value = null;

  public GcdProcessHolder ()
  {
  }

  public GcdProcessHolder (gcd.Starter.GcdProcess initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = gcd.Starter.GcdProcessHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    gcd.Starter.GcdProcessHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return gcd.Starter.GcdProcessHelper.type ();
  }

}
